### ISSUE TITLE
import clr clashes with pythonnet package

### ISSUE THREAD

**Issue by den-run-ai** [lmittmann/clr#1]
https://github.com/pythonnet/pythonnet/issues/388

pythonnet has been available since 2003.

**Comment by vmuriart** [comment]
The name clashes with `IronPython` which uses [`import clr`](https://en.wikipedia.org/wiki/IronPython#Examples) as its import hook.

**Comment by lmittmann** [comment]
I noticed the package name conflict after publishing. Does this affect your build or installation process?

My understanding of pythonnet/pythonnet#388 is, that `pip install clr` was executed instead of `pip install pythonnet`, right?

**Comment by den-run-ai** [comment]
This does not affect our build or installation, but new pythonnet users will keep bumping into this issue by incorrectly assuming that `pip install clr` is necessary before `import clr`.

Would you mind renaming your package before it is too late? I see that it is only about one month old?

**Comment by lmittmann** [comment]
It is actually really hard to find a good 3 letter name. How about a little compromise:

- We update the [pythonnet/README.md](https://github.com/pythonnet/pythonnet/blob/master/README.md) to show some installation instructions, since people who wrongly install `clr` instead of `pythonnet` just got a different error, before I published my package.
- I will update the `AttributeError` to show a more explanatory error message, pointing to `pythonnet`

**Comment by vmuriart** [comment]
The problem is for users that install both like the original issue that made us detect it.

**Comment by lmittmann** [comment]
I thought the original issue was that a new pythonnet user installed the wrong package.

**Comment by den-run-ai** [comment]
import clr
import System

How would you report error on this?

**Comment by lmittmann** [comment]
`System` is a toplevel module of pythonnet?

**Comment by den-run-ai** [comment]
"import clr" hooks up CPython with .NET runtime. "import System" imports
main .NET assembly namespace into CPython.

Same imports are used in IronPython.

**Comment by lmittmann** [comment]
The `AttributeError` caused by `clr.AddReference` can be easily detected. Detecting the `import System` error might be more complicated. I will have a look on how this "hook up" is done, it might be also catchable.

**Comment by vmuriart** [comment]
We modify the import hook to inject .net libraries. In this case it would
be difficult to decide if it's an import error because of clr vs pythonnet
or if the user is trying to import libraries from Python or from GAC

**Comment by vmuriart** [comment]
You can do a quick Google lookup of "import clr" to see the amount of usage
it has.

**Comment by filmor** [comment]
@lmittmann Please take a stance on this now.

Are you going to rename your library? You are clashing with both Python.NET and IronPython and are causing confusion for people using `pip` directly. If not, please at least say so now and we will put the corresponding information into our Readme and entry page.

Please don't try to hack around this by capturing `import System` or `clr.AddReference`.

**Comment by lmittmann** [comment]
I will rename the library later today. I am not sure about the best way to transfer ownership of a pypi package though. Any ideas @denfromufa @vmuriart @filmor?

**Comment by filmor** [comment]
Does this link work? https://pypi.python.org/pypi?:action=role_form&package_name=clr

You can add one of us as owners and we will handle it from there.

Many thanks for the renaming :)

**Comment by lmittmann** [comment]
That worked, you should have access now.

**Comment by koubaa** [comment]
@lmittmann could you please unlist clr from pypi?
