### ISSUE TITLE
How to turn off bold?

### ISSUE THREAD

**Issue by mdrx-io** [lmittmann/clr#2]
Great package! Usability question:

Say I've got:
```
print(style.white('•', style.bold.white(' [{}] {}'.format(name, style.dim.white('{}'.format(msg))))))
```
I want to replace 'dim' with just the normal, unbolded text... but I can't figure out how to do that. i.e., I want to turn off bold after using it in the same line.

**Comment by lmittmann** [comment]
Hi @crunchex, actually you ran into two issues with my package at the same time:

1. I have not added support for nesting styles using `%` or `.format()` yet.
2. There is no way to reset only the modifier style. A possible workaround would be to use `style.default`  which will reset (if nested) all styles of the outer style .

For now the best **solution** for your problem would be:

```py
print(style.white('•', style.bold('  ['), name, style.bold('] '), msg, sep=''))
```

or simply

```py
print('•', style.bold('  ['), name, style.bold('] '), msg, sep='')
```

if `white` is your terminals default.
